name: CI

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.os }} • py ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "pypy-3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: |
          uv pip install -e .
          uv pip install ruff mypy pytest pytest-cov

      - name: Lint (ruff)
        run: uv run ruff check src tests

      - name: Format check (ruff)
        run: uv run ruff format --check src tests

      - name: Type check (mypy)
        run: uv run mypy src

      - name: Tests with coverage (enforced)
        if: hashFiles('tests/**/*.py') != ''
        run: uv run pytest --cov=jetstream --cov-report=term-missing --cov-fail-under=90 -q

      - name: Tests (no test files)
        if: hashFiles('tests/**/*.py') == ''
        run: echo "No tests found; skipping coverage gate." && uv run pytest -q || true
